TÉRMINOS Y CONDICIONES

Los siguientes son los términos y condiciones que “PídeloTú”, marca registrada de MASTER DASH, S. DE R.L. DE C.V.1 otorga para el uso de sus servicios:

A) NATURALEZA DEL CONTRATO.  
1.- Se entenderá que todo aquel que descargue la aplicación propiedad de “PídeloTú”, registre una cuenta en su plataforma/aplicación y/o haga uso de su plataforma o solicite los servicios que éste ofrece al público, está de acuerdo en someterse a los términos y condiciones descritos en éste documento, adquiriendo así dicha(s) persona(s) la calidad de “USUARIO” conforme a los presentes términos y condiciones, al contrato de usuario final y cualquier otro reglamento o disposición que “PídeloTú”o MASTER DASH, S. DE .R.L. DE C.V. haga disponible a sus Usuarios por éste o cualquier otro medio; de manera plena y sin reservas.

2.- “PídeloTú”y MASTER DASH, S. DE R.L. DE C.V. otorgan a sus usuarios la licencia de uso de su programa, aplicación y plataforma web conforme a las presentes condiciones de uso, no pudiendo sin embargo: reproducir, modificar, o preparar obras derivadas sobre los servicios, salvo lo expresamente autorizado por “PídeloTú”o MASTER DASH, S. DE R.L. DE C.V.  Cualquier dicha autorización no constituirá cesión a favor de o adquisición por parte del Usuario de cualquier derecho de propiedad industrial, intelectual o similar, tanto en territorio nacional como extranjero.  

3.- “PídeloTú”y/o MASTER DASH, S. DE R.L. DE C.V. podrán otorgan cambios y modificaciones a su aviso legal, políticas, términos y condiciones y cualquier otro documento legal o constitutivo en cualquier momento y sin previo aviso.  Será por lo tanto responsabilidad de los usuarios revisar las últimas actualizaciones que a dichos documentos se realicen.  “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V. tendrá la opción mas no la obligación de avisar a sus usuarios sobre cualquier cambio en sus políticas, términos y condiciones, aviso legal o en cualquier otro reglamento, contrato o documento constitutivo.

4.- Queda estrictamente prohibido cualquier uso ilegal, inadecuado y no autorizado de la aplicación, página de internet, plataforma y cualquier otra obra o creación relacionada, así como de cualquier cuenta, clave o password o de cualquier información relacionada con lo anterior; pudiendo “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V. llevar a cabo las acciones legales necesarias a fin de preservar su buen nombre, reputación, prestigio, negocio e intereses.   El usuario acuerda por este medio mantener libre e ileso a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V. de cualquier responsabilidad por cualquier uso ilegal, inadecuado o no autorizado de la aplicación, página de internet, plataforma y servicios que haga el usuario de conformidad con lo anterior y teniendo además la obligación de indemnizar a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V. por cualquier pérdida, litigio o controversia que se llegase a causar como consecuencia de lo anterior. 

5.- El usuario excluye y exonera a “PídeloTú” y/o MASTER DASH, S. DE R.L. D EC.V. por cualquier responsabilidad civil, administrativa, penal, por daños y perjuicios y demás responsabilidad por el uso ilegal, inadecuado y no autorizado que el Usuario realice de la aplicación, página de internet, plataforma o cualquier otra obra y creación relacionada y derivada del servicio o sus licencias, y que dañe o pueda dañar, menoscabar, empobrecer o impactar de cualquier manera negativa a terceras personas. 

6.- Los usuarios manifiestan someterse a la legislación vigente en la ciudad de Torreón, Coahuila así como a la jurisdicción de los tribunales de la ciudad de Torreón, Coahuila.  Cualquier disputa que se origine del presente deberá ser despachada y ventilada por medio del Procedimiento de Arbitraje en la ciudad de Torreón, Coahuila; o cualquier otro medio que “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V. estime conveniente; renunciando el Usuario al fuero y jurisdicción que le pudiera corresponder en virtud de su domicilio o cualquier otro elemento.

B).- OBJETIVO DE LA APLICACIÓN.
1.- La aplicación, página de internet, plataforma y obras derivadas creadas o bajo licencia a favor de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V tendrán por objetivo facilitar la comanda de ciertos bienes y servicios por medios electrónicos, así como su entrega al domicilio que el Usuario indique siempre y cuando dicha localidad se encuentre disponible en el área geográfica de entrega de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V.

2.- Al registrarse y obtener una cuenta de “PídeloTú” , los usuarios tendrán acceso a solicitar la entrega a domicilio de ciertos bienes y servicios que se ofertarán desde la aplicación, página de internet, plataforma u obras derivadas propiedad de “PídeloTú” .  Dicha plataforma indicará el costo del bien o servicio solicitado por el usuario, así como el costo de envío y el tiempo aproximado de entrega.  El tiempo aproximado de entrega es el tiempo en que conforme a situaciones normales de operación, se estima dicho bien o servicio requerido por el usuario llegue a su destino.  Lo anterior es exclusivamente informativo y no creará obligaciones ni responsabilidades a “PídeloTú” y/o para realizar la entrega en dicho tiempo estimado.

3.- Ciertos bienes y servicios pudieran estar disponibles de manera limitada o por tiempo limitado conforme a los términos y condiciones propios del negocio que los oferta.  Es responsabilidad del Usuario corroborar que el bien o servicio que solicita a través de la plataforma propiedad de “PídeloTú” se encuentra disponible para su entrega conforme lo solicite el usuario.  “PídeloTú” no se hace responsable por ningún daño o perjuicio que puedan afectar al usuario por dichas circunstancias.  

4.- “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V han diseñado una aplicación, página de internet, y plataforma desde la cual se pueden ofertar a los usuarios un gran catálogo de bienes y servicios relacionados en su mayoría con la alimentación y restaurantes.  El usuario podrá elegir desde la plataforma y/o aplicación que “PídeloTú” ponga a disposición de aquél bajo licencia, el bien o servicio de su conveniencia.  La misma plataforma y/o aplicación dará al usuario el total a pagar, incluyendo un sobreprecio por los gastos de envío.  El gran total deberá ser liquidado por el Usuario a través de medios electrónicos.  “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V han contratado a un tercer agente a fin de recaudar los pagos que se generen por las comandas solicitadas por los usuarios.  Dichos medios de pago no son propiedad de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V por lo que, en caso de cualquier controversia, el Usuario deberá ventilar dicha controversia directamente con el proveedor de dichos servicios de cobro.  El objetivo de las políticas internas de atención al cliente de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V es siempre brindar el mejor servicio a sus usuarios, por lo que “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V mantendrá un monitoreo de la controversia, apoyando tanto al usuario como al proveedor de servicios de recolección de pagos a fin de arreglar dicha controversia lo antes posible y de la mejor manera posible.  El Usuario libera de toda responsabilidad civil, administrativa, penal y similar a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V por cualquier daño o perjuicio que se origine con motivo de dicha controversia, debiendo el usuario mantener ileso a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V por cualquier responsabilidad u actos que al usuario se le pudieran imputar.
 
5.- Al momento en que el usuario origine una comanda de bien o servicio desde la plataforma o aplicación de “PídeloTú”, el proveedor de los bienes o servicios elegidos por el usuario recibirán una notificación y la misma aplicación o plataforma indicará al usuario el tiempo estimado de preparación y entrega de lo que ha solicitado, así como en la etapa en la cual se encuentra, a saber: preparación, en espera de entregar a repartidor, en repartición, o entregado.  El tiempo que la plataforma o aplicación indiquen como tiempo de preparación o de entrega son meramente de carácter informativo y “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V no se hacen responsable de cualquier daño o perjuicio que llegare a afectar al usuario por cualquier entrega en demás del tiempo indicado.  El usuario libera expresamente a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V de cualquier responsabilidad, indemnizándole y manteniéndole ileso de cualquier controversia que se genere al respecto.

6.- Se sobreentiende que los bienes, productos y servicios ofertados a partir de la plataforma y/o aplicación de “PídeloTú”, NO SON DE SU PROPIEDAD, por lo que “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V no se hace responsable por cualquier controversia que pueda existir con motivo de la calidad, presentación, consistencia ni ningún otro factor inherente al bien, producto o servicio ofertado.  Dado que el objetivo de las políticas internas de atención al cliente de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V es siempre brindar el mejor servicio a sus usuarios, “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V mantendrá un monitoreo de cualquier controversia que se pudiera suscitar entre el usuario y el proveedor del bien o servicio solicitado por el usuario.  Tanto el usuario como el proveedor de bienes y servicios liberan de toda responsabilidad civil, administrativa, penal y similar a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V por cualquier cargo, daño o perjuicio que se origine con motivo de dicha controversia, debiendo además mantenerle ileso por cualquier acto u acción imputables tanto al usuario como al proveedor de bienes y servicios.

7.- Ciertos productos y servicios disponibles desde la aplicación y/o plataforma “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V podrán estar sujetos a reglamentos y/o condiciones especiales o particulares.  Es responsabilidad del usuario comprobar que para la solicitud de tales productos y servicios, cuenta Y cumple con los requisitos tanto legales como por parte del proveedor de bienes y servicios como de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V  sin que sea responsabilidad de éste último asegurar que el usuario cumple con dichas normas, descargando a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V así como a sus afiliados comerciales de cualquier responsabilidad legal, civil o moral.

8.- El usuario reconoce que al ingresar en la página de internet, aplicación y plataforma de PIDELO TÚ, acepta y consiente expresamente el uso, descarga e instalación de cookies.  

9.-  Queda estrictamente prohibido cualquier uso ilegal, inadecuado y no autorizado de la aplicación, página de internet, etc. así como de cualquier cuenta, clave o password o de cualquier información relacionada con lo anterior.  Acordando el usuario mantener libre e ileso a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V de cualquier responsabilidad de conformidad con lo anterior y debiendo además indemnizar a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V por cualquier pérdida o ¿? Que llegare a provocarse como consecuencia de lo anterior.  PIDELO TÚ / MASTER DASH, S. DE R.L. DE C.V. no se hace responsable por cualquier daño o perjuicio que pueda afectar al usuario con motivo de uso de software malicioso o por cualquier acción de hackeo, según se entiende específicamente conforme a los manuales informáticos vigentes y que a manera general significa el acto malicioso de terceras personas a fin de robar la identidad o datos de los usuarios y/o de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V El usuario manifiesta su acuerdo y libera y mantiene ileso de cualquier responsabilidad civil, legal o moral sea del carácter que fuere a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V por cualquier acto malicioso del denominado “hackeo” o fraudes virtuales similares que tengan como objetivo el robo de identidad, información de usuarios o que constituyan un acto parcial o encaminado a su realización definitiva.

10.-  Para la prestación de los servicios ofertados por “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V, este hace uso de ligas (“links”) a sitios externos, mismos cuyo contenido no es revisado por “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V  ni se hace responsable de dichos contenidos.

11.- Todas las notificaciones realizadas por “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V se realizan a manera de informar a los usuarios sobre cualquier cambio o modificación en las políticas de los sitios, aplicación o plataforma propiedad de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V.  Sin embargo, su realización o falta de esta no deberá entenderse como la renuncia por parte de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V a realizar cualquier cobro o modificación a los servicios brindados.

12.-“PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V toma un especial cuidado en que la información contenida en su aplicación y plataforma sea la correcta y se encuentre actualizada; sin sin incurrir en responsabilidad alguna en caso de que no fuere.  

13.-“PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V podrá suspender a usuarios o concluir con el servicio brindado sin previo aviso ni limitación alguna, sea cual fuere la causa, y sin que “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V incurra en responsabilidad alguna.

14.- Será responsabilidad del Usuario mantener la confidencialidad de su clave o password para acceder a la aplicación o plataforma de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V.  Se entiende que el ingreso de dicha clave en el sistema de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V verifica la identidad del usuario que registró su cuenta ante “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V.  “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V no se hace responsable de cualquier mal manejo, robo de identidad ni fraude al respecto.

15.-“PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V es titular y propietario de todos los derechos y licencias sobre el software utilizado por éste, a excepción de los productos y servicios ofertados que no son de su propiedad, ni de los vehículos que realizan las entregas de los mismos.  Ningún material podrá ser reproducido ni utilizado por el usuario sin el consentimiento por escrito de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V

C).-  PAGOS.
1.- Tras generarse la comanda por los bienes o servicios solicitados por el usuario, “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V pone a disposición del usuario varios canales de pago a través de su aplicación, plataforma o página de internet “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V ha contratado a un agente de recaudación de pagos por medios electrónicos, los cuales no son propiedad de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V por lo que cualquier pago realizado por el usuario se entenderá como un pago realizado por el usuario al proveedor de los servicios de cobro. 

2.- El uso de los métodos de pago propuestos se realiza bajo el propio y exclusivo riesgo del usuario, liberando de cualquier cargo o responsabilidad a “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V
3.- Se sobreentiende que cualquier reclamo, aclaración o inconformidad referente al cobro y/o pago de los servicios solicitados a través de la aplicación, plataforma y/o página web de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V será atendido y resuelto finalmente por el mismo agente/proveedor de servicios de recaudación de pagos.

3.- “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V mantiene el compromiso de brindar servicios de calidad a los usuarios de sus servicios, por lo que cualquier inconformidad en el cobro y pago de los bienes o servicios solicitados por los usuarios será atendida y monitoreada por “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V canalizando en todo momento dicha inconformidad con el agente de cobros.  

4.- “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V se reserva el derecho de establecer, eliminar o revisar los cargos por cualquiera de los bienes o servicios adquiridos por medio de los servicios prestados por éste.

D).- MANEJO DE INFORMACIÓN PERSONAL.
1.- “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V mantiene políticas de estricto respeto a la confidencialidad de los datos de sus usuarios, para lo cual ha emitido su Aviso de Privacidad.  Para mayor información, favor de consultar el Aviso de Privacidad aquí: http://pidelotu.mx/avisodeprivacidad.

2.- Dadas las características del internet “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V no se hace responsable de ningún fraude o robo de identidad ni por el contagio a equipo del usuario por cualquier virus, malware o programas sospechosos o que puedan tener un impacto negativo en el usuario o su equipo.

3.-  “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V  no es propietario de los datos e información que se comparta, y sólo lo recaba para fines de facilitar el pedido de bienes servicios que realicen los usuarios, así como para el pago que se vaya a realizar por medio de las plataformas que “ONEPAY”, agente de cobros contratado por “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V ponga a disposición de los usuarios mediante la aplicación o páginas de internet de “PídeloTú” y/o MASTER DASH, S. DE R.L. DE C.V.


